[project]
name = "Cohort8-DS-5"
version = "0.1.0"
description = "Team project repository"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "pandas>=2.3.2",
    "numpy>=2.3.3",
    "matplotlib>=3.10.6",
    "seaborn>=0.13.2",
    "plotly>=6.5.2",
    "scikit-learn>=1.7.2",
]